### ISSUE TITLE
expo 실행 시 Network response timed out. 문구 발생

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#1]
### 버그 내용 간단히
expo 실행 시 Network response timed out. 문구 발생

> 안드로이드 기기에서 expo를 실행할 때 Network response timed out. 문구가 나타납니다.

### TODO 목록
- [ ] expo start --tunnel 명령어로 실행 시도
- [x] CMD를 통해 해결 방법 시도
- [ ] 문제 해결 후 테스트 및 확인

**Comment by kimsongmok** [comment]
참고 바람
https://velog.io/@reveloper-1311/React-Native-Expo-Network-response-timed-out.-%EC%97%90%EB%9F%AC

**Comment by kimsongmok** [comment]
expo start --tunnel 명령으로 실행

**Comment by kimsongmok** [comment]
CMD로 해결하는 방법

https://velog.io/@damin1025/React-Native-Expo-Network-Timeout-Error-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0
