### ISSUE TITLE
Navbar 구현 요청

### ISSUE THREAD

**Issue by scove03** [semicolonsknu/knubus#11]
> 네비게이션 바를 구현하여 페이지 전환 기능을 추가합니다.

### TODO 목록
- [x] Navbar 컴포넌트 생성 및 UI 구현
- [x] 각 버튼에 페이지 전환 함수 연결
- [x] StackNavigation 함수 적용하여 페이지 전환 구현

**Comment by sugoring** [comment]
Container not exist 에러

**Comment by sugoring** [comment]
기능 구현 예시:

import 한 컴포넌트를 불러오고,
텍스트를 버튼 형식으로 바꿔서, 버튼에 함수 속성을 넣으면 될거같아.

함수속성에 버튼을 누르면 컴포넌트가뜨는거만 우선 구현하면 될듯!

그거 전달해주면 내가 희원이가 한거랑 합쳐서 상태관리로 전역 페이지에서 
네비바가 누르면 그 페이지가 유지되도록 할꺼야!

**Comment by sugoring** [comment]
> Container not exist 에러

container 컴포넌트 활용 불필요

**Comment by scove03** [comment]
네비바 구현중 Stack 파일에 StackNavigation 함수를 적용해야하는데 본래는 App에다 다른코드 없이 넣는데 이건 어떻게 해야하는지 잘 모르겠음..

**Comment by scove03** [comment]
코딩방법은 인프런 강의와 책을 기반으로 했고 인터넷에서 참고한건
1.
https://velog.io/@sunohvoiin/React-Native-React-Navigation
2.
https://velog.io/@slobber/React-native-navigation-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-%EA%B0%9C%EB%B0%9C%ED%95%98%EA%B8%B0
3.
https://eunbin00.tistory.com/41

**Comment by sugoring** [comment]
웹에서 페이지를 router 이용해서 페이지를 이동하는 것과 달리 stack 형식으로 현재 view 에서 위로 쌓이는 형식

**Comment by sugoring** [comment]
공식 문서 https://reactnavigation.org/docs/getting-started/
