### ISSUE TITLE
현재 시간 구현 요청

### ISSUE THREAD

**Issue by scove03** [semicolonsknu/knubus#13]
> 현재 시간을 보여주고, 다음 이전 버튼을 생성합니다.

### TODO 목록
- [x] 현재 시간 표시 기능 구현
- [x] 다음 시간으로 이동 버튼 추가
- [x] 이전 시간으로 이동 버튼 추가

**Comment by sugoring** [comment]
현재 시간을 보여주고, 다음 이전 버튼을 생성함
