### ISSUE TITLE
logo 및 기타 이미지 변경 요청

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#14]
> knu 로고를 활용하여 logo 및 기타 이미지를 생성하고, 변경합니다.

### TODO 목록
- [ ] adaptive-icon.png 생성 및 변경
- [x] favicon.png 생성 및 변경
- [x] icon.png 생성 및 변경
- [x] Logo.png 생성 및 변경
- [x] menu.png 생성 및 변경
- [x] splash.png 생성 및 변경
