### ISSUE TITLE
애플리케이션 화면 구조 설계 요청

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#2]
> 애플리케이션 구성에 맞는 화면 구조를 설계합니다.

### TODO 목록
- [x] 오늘 날짜와 전일, 후일로 이동하는 버튼 추가
- [x] 현재 시각 표시 기능 구현
- [x] 휴일 일정 확인 및 휴일 텍스트 표시 기능 구현
- [x] 회차 정보와 운행시간표 표시
- [x] 이전 및 다음 회차로 이동하는 버튼 추가
- [x] 운행 노선도 지도 삽입

**Comment by sugoring** [comment]
![image](https://github.com/semicolonsknu/knubus/assets/113340465/b4526c5b-5b67-4883-8b65-de7be8c70502)
