### ISSUE TITLE
React Native Navigation 구현 요청

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#21]
> react-navigation을 사용하여 앱 내 화면 간 네비게이션 기능을 구현합니다.

### TODO 목록
- [x] App.js에서 Header.js 및 Navigation.js 임포트
- [x] Navigation.js에서 react-navigation을 사용하여 HomeScreen.js, MapScreen.js, TimeScreen.js 정의
- [x] Header.js에서 로고 교체 및 클릭 시 링크 연결
- [ ] Footer.js에 광고 기능 구현 (예정)

**Comment by sugoring** [comment]
전체 기본 기능 구현

App.js: Header.js및Navigation.js`을 임포트함.

Navigation.js: react-navigation(tap screen)를 활용하여 애플리케이션 정의. (HomeScreen.js, MapScreen.js, TimeScreen.js)

Header.js: 헤더.

// 로고를 클릭하면 https://wwwk.kangwon.ac.kr/www/contents.do?key=2414& 링크가 인터넷 앱에서 열리도록 수정 @구희원

// 로고 교체 필요 @구희원

Footer.js: 푸터. 광고 기능 구현 예정

HomeScreen.js: 메인 페이지, 현재 시각 표시. Holiday.js와 Round.js를 임포트하고, 상태를 넘겨줌.

// 휴일인 경우 전체 상태 지정해야함.

Holiday.js: 현재 날짜에 따른 휴일 여부를 표시. 이전 및 다음 날짜로 이동 가능.
Round.js: 현재 회차와 해당 회차의 운행 시간표를 표시. 이전 및 다음 회차로 이동 가능.
// 1회차: 운영 예정[0:0 ~ 8:29] / 운영 중[8:30 ~ 8:53]
// 2회차: 운영 예정[8:54 ~ 9:29] / 운영 중[9:30 ~ 9:53]
// 3회차: 운영 예정[9:54 ~ 9:59] / 운영 중[10:00 ~ 10:23]
// 4회차: 운영 예정[10:24 ~ 11:29] / 운영 중[11:30 ~ 11:53]
// 5회차: 운영 예정[11:54] ~ [11:59] / 운영 중[12:00 ~ 12:23]
// 6회차: 운영 예정[12:24 ~ 12:59] / 운영 중[13:00 ~ 13:23]
// 7회차: 운영 예정[13:24 ~ 14:29] / 운영 중[14:30 ~ 14:53]
// 8회차: 운영 예정[14:54 ~ 13:59] / 운영 중16:00 ~ 16:23]
// 9회차: 운영 예정[14:24 ~ 16:29] / 운영 중[17:30 ~ 17:53]
// 10회차: 운영 예정[17:54 ~ 17:59] / 운영 중[18:00 ~ 18:23]
MapScreen.js: 전체 운행 노선도를 표시.

TimeScreen.js: 전체 운행 시간표를 표시.
// 타임테이블 데이터를 작성한다. @최수영
// 운행 시간표
// 구분 미래도서관 동생대2호관 경영대2호관 미래광장 백록관 기숙사(회차) 함인섭광장 미래광장 경영대광장 경영대 2호관 의생대 미래도서관
// 1회차 8:30 8:32 8:34 8:36 8:38 8:43 8:45 8:47 8:49 8:51 8:53 8:53
// 2회차 9:30 9:32 9:34 9:36 9:38 9:43 9:45 9:47 9:49 9:51 9:53 9:53
// 3회차 10:00 10:02 10:04 10:06 10:08 10:13 10:15 10:17 10:19 10:21 10:23 10:23
// 4회차 11:30 11:32 11:34 11:36 11:38 11:43 11:45 11:47 11:49 11:51 11:53 11:53
// 5회차 12:00 12:02 12:04 12:06 12:08 12:13 12:15 12:17 12:19 12:21 12:23 12:23
// 6회차 13:00 13:02 13:04 13:06 13:08 13:13 13:15 13:17 13:19 13:21 13:23 13:23
// 7회차 14:30 14:32 14:34 14:36 14:38 14:43 14:45 14:47 14:49 14:51 14:53 14:53
// 8회차 16:00 16:02 16:04 16:06 16:08 16:13 16:15 16:17 16:19 16:21 16:23 16:23
// 9회차 17:30 17:32 17:34 17:36 17:38 17:43 17:45 17:47 17:49 17:51 17:53 17:53
// 10회차 18:00 18:02 18:04 18:06 18:08 18:13 18:15 18:17 18:19 18:21 18:23 18:23
