### ISSUE TITLE
운행노선도 지도 새로 제작하기 요청

### ISSUE THREAD

**Issue by HeHelee** [semicolonsknu/knubus#26]
> Figma 툴을 이용하여 새로운 운행노선도를 제작하고, 각 정류장 클릭 시 팝업으로 사진이 뜨도록 설정합니다.

### TODO 목록
- [x] Figma 툴을 이용하여 새로운 지도 제작
- [x] 지도의 제목을 '운행노선도'로 지정
- [x] 동문, 후문, 정문으로 구분하여 지도 제작
- [x] 정류장의 크기 확대 및 가독성 개선 (4/1일까지)
- [x] 정류장 클릭 시 사진이 뜨도록 팝업 제작
- [x] 각 정류장에 해당하는 이미지 수집 및 준비
- [x] 각 정류장에 이미지를 연결하여 클릭 시 해당 이미지 팝업 설정 (4/3일까지)

**Comment by sugoring** [comment]
- 운행도 순서대로 그룹 순서의 흐름이 진행되는 것이 협업하는데 효율 적임
- 줄임말 보다 다같이 이해할 수 있는 단어를 쓰는 것이 좋음 (미광 > 미래광장)
- 파일의 양이 많아지면, 새로 폴더에 정리하는 것이 효율적임
