### ISSUE TITLE
TimeScreen 구현 기능 요청

### ISSUE THREAD

**Issue by scove03** [semicolonsknu/knubus#30]
> 테이블을 하드코딩하는 대신, JSON 형식의 데이터를 활용하여 TimeScreen을 구현합니다.

### TODO 목록
- [x] JSON 형식의 데이터 준비 및 로드
- [x] TimeScreen UI 구성
- [x] JSON 데이터를 활용한 동적 테이블 생성

**Comment by sugoring** [comment]
테이블을 하드코딩 하는 것보다, json 형식으로 된 데이터를 활용하는 것이 좋음.
