### ISSUE TITLE
전체 기능 리팩토링 요청

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#37]
> 타임라인 위치 이동 표시, 지도 위치 조정, 이미지 폴더 변경, 시간표 UI 및 내용 수정, 로딩 화면 구현

### TODO 목록
- [ ] 타임라인 실시간 위치 이동 표시 기능 구현
- [x] 지도 위치 상대위치로 조정 및 이미지 폴더 변경
- [x] 시간표 UI 및 내용 수정
- [x] 로딩 화면 구현

**Comment by sugoring** [comment]
#수정사항1
timeline 실시간으로 위치 이동하는 것 보여주기

**Comment by sugoring** [comment]
#수정사항2
map 위치 상대위치로 조정
map 에서 활용되는 이미지 폴더 변경

**Comment by sugoring** [comment]
#수정사항3
timetable ui 수정
timetable 표 내용 수정

**Comment by sugoring** [comment]
#수정사항4
로딩화면 구현
