### ISSUE TITLE
빌드 시 Google API를 통한 지도 출력 오류

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#45]
> 빌드 후 Google Maps가 제대로 출력되지 않습니다.

### TODO 목록
- [x] Google API 키 및 설정 확인
- [x] 네트워크 권한 및 설정 검토
- [x] 코드 수정 및 테스트

**Comment by semicolonsknu** [comment]
Install dependencies
20s


Running "yarn install" in /home/expo/workingdir/build/frontend directory
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/react-native-elements/react-native-elements.git
Directory: /home/expo/workingdir/build/frontend
Output:
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install exited with non-zero code: 128

Fail build
1s


Build failed

yarn install exited with non-zero code: 128

**Comment by sugoring** [comment]
> Install dependencies 20s
> 
> Running "yarn install" in /home/expo/workingdir/build/frontend directory yarn install v1.22.19 warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... [2/4] Fetching packages... error Command failed. Exit code: 128 Command: git Arguments: ls-remote --tags --heads ssh://[git@github.com](mailto:git@github.com)/react-native-elements/react-native-elements.git Directory: /home/expo/workingdir/build/frontend Output: Host key verification failed. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. yarn install exited with non-zero code: 128
> 
> Fail build 1s
> 
> Build failed
> 
> yarn install exited with non-zero code: 128

yarn과 npm을 혼용하여 사용하여 나타난 결과 
- package-lock.json 과 yarn.lock 을 제거한다

**Comment by sugoring** [comment]
yarn은 설치한 패키지와 종속되는 패키지를 공통적으로 사용할 때 일렬로 나열한 뒤 설치 패키지로 링크하는 방식으로. 패키지 중복이 제거되어 적은 용량으로 빠른 실행을 꾀할 수 있으나 네이티브 및 yarn을 고려하지 않은 버전 관리로 인한 드문 케이스로 패키지 충돌이 있을 수 있다.

npm은 각 설치한 패키지별로 서브패키지를 이루는 형식으로, 각 설치한 패키지의 독립성이 보장되지만 패키지 중복으로 인한 크기가 전체적으로 커진다.

**Comment by sugoring** [comment]
npm 캐시 지우기 - npm cache verify
Yarn 캐시 지우기 - yarn cache clean

**Comment by sugoring** [comment]
https://docs.expo.dev/versions/latest/sdk/build-properties/?redirected

**Comment by sugoring** [comment]
package-lock.json 파일의 중요성
프로젝트에 사용될 npm package들은 package.json 파일로 관리된다.
이때 npm install 명령어로 package들이 설치가 되면 package-lock.json 파일이 생성된다.

package-lock.json 파일은 작업자의 개발환경에서 npm install 할 때 종속성 관련 정보가 package-lock.json 파일에 반영된다. npm 을 이용하여 개발을 하다보면 이 종속성 문제가 상당히 골치가 아플때가 많다.

예를 들어 A란 package의 최신 버전이 릴리즈 되어서 A package를 사용하려고 해도 다른 package에서 종속성에 문제가 발생하면 A package를 쓰지 못하거나 A package와 종속성이 관련된 package들를 찾아서 같이 버전업 해줘야 사용 가능하다.

따라서, Git 과 같은 코드 형상 관리 시스템을 이용한다면 package-lock.json 파일도 함께 Commit 해 주어야 다른 개발 환경에서도 동일한 버전의 npm 라이브러리 관리가 가능해진다.

**Comment by sugoring** [comment]
Running 'gradlew :app:assembleRelease' in /home/expo/workingdir/build/frontend/android
Downloading https://services.gradle.org/distributions/gradle-8.3-all.zip
10
%.
20%.
30%.
40%.
50
%.
60%.
70%.
80%.
90%.
100%
Welcome to Gradle 8.3!
Here are the highlights of this release:
 - Faster Java compilation
 - Reduced memory usage
- Support for running on Java 20
For more details see https://docs.gradle.org/8.3/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
> Configure project :
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC
> Configure project :expo-modules-core
Warning: Errors during XML parse:
Warning: Additionally, the fallback loader failed to parse the XML.
Checking the license for package NDK (Side by side) 25.1.8937393 in /home/expo/Android/Sdk/licenses
License for package NDK (Side by side) 25.1.8937393 accepted.
Preparing "Install NDK (Side by side) 25.1.8937393 v.25.1.8937393".
"Install NDK (Side by side) 25.1.8937393 v.25.1.8937393" ready.
Installing NDK (Side by side) 25.1.8937393 in /home/expo/Android/Sdk/ndk/25.1.8937393
"Install NDK (Side by side) 25.1.8937393 v.25.1.8937393" complete.
"Install NDK (Side by side) 25.1.8937393 v.25.1.8937393" finished.
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Configure project :expo
Using expo modules
  - expo-constants (15.4.6)
- expo-file-system (16.0.9)
  - expo-font (11.10.3)
  - expo-keep-awake (12.8.2)
  - expo-modules-core (1.11.13)
  - expo-modules-core$android-annotation (1.11.13)
  - expo-modules-core$android-annotation-processor (1.11.13)
> Configure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3
WARNING: The specified Android SDK Build Tools version (31.0.0) is ignored, as it is below the minimum supported version (33.0.1) for Android Gradle Plugin 8.1.1.
Android SDK Build Tools 33.0.1 will be used.
To suppress this warning, remove "buildToolsVersion '31.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (31.0.0) is ignored, as it is below the minimum supported version (33.0.1) for Android Gradle Plugin 8.1.1.
Android SDK Build Tools 33.0.1 will be used.
To suppress this warning, remove "buildToolsVersion '31.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Checking the license for package Android SDK Build-Tools 33.0.1 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 33.0.1 accepted.
Preparing "Install Android SDK Build-Tools 33.0.1 v.33.0.1".
"Install Android SDK Build-Tools 33.0.1 v.33.0.1" ready.
Installing Android SDK Build-Tools 33.0.1 in /home/expo/Android/Sdk/build-tools/33.0.1
"Install Android SDK Build-Tools 33.0.1 v.33.0.1" complete.
"Install Android SDK Build-Tools 33.0.1 v.33.0.1" finished.
Checking the license for package Android SDK Platform 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision 1)".
"Install Android SDK Platform 31 (revision 1)" ready.
Installing Android SDK Platform 31 in /home/expo/Android/Sdk/platforms/android-31
"Install Android SDK Platform 31 (revision 1)" complete.
"Install Android SDK Platform 31 (revision 1)" finished.
> Task :react-native-community_netinfo:preBuild UP-TO-DATE
> Task :react-native-community_netinfo:preReleaseBuild UP-TO-DATE
> Task :react-native-community_masked-view:preBuild UP-TO-DATE
> Task :react-native-community_masked-view:preReleaseBuild UP-TO-DATE
> Task :react-native-community_netinfo:mergeReleaseJniLibFolders
> Task :react-native-community_netinfo:mergeReleaseNativeLibs
NO-SOURCE
> Task :react-native-community_netinfo:stripReleaseDebugSymbols
NO-SOURCE
> Task :expo:generateExpoModulesPackageList
> Task :react-native-community_netinfo:generateReleaseResValues
> Task :react-native-community_netinfo:extractDeepLinksForAarRelease
> Task :react-native-community_netinfo:generateReleaseBuildConfig
> Task :react-native-community_netinfo:generateReleaseResources
> Task :react-native-community_netinfo:packageReleaseResources
> Task :react-native-community_masked-view:mergeReleaseJniLibFolders
> Task :react-native-community_masked-view:mergeReleaseNativeLibs NO-SOURCE
> Task :react-native-community_masked-view:stripReleaseDebugSymbols NO-SOURCE
> Task :react-native-community_netinfo:parseReleaseLocalResources
> Task :react-native-community_masked-view:generateReleaseResValues
> Task :react-native-community_masked-view:extractDeepLinksForAarRelease
> Task :react-native-community_masked-view:generateReleaseBuildConfig
> Task :react-native-community_masked-view:generateReleaseResources
> Task :react-native-community_masked-view:packageReleaseResources
> Task :react-native-community_masked-view:parseReleaseLocalResources
> Task :react-native-community_masked-view:copyReleaseJniLibsProjectAndLocalJars
> Task :react-native-community_netinfo:copyReleaseJniLibsProjectAndLocalJars
> Task :react-native-community_masked-view:processReleaseManifest
package="org.reactnative.maskedview" found in source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/@react-native-community/masked-view/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="org.reactnative.maskedview" from the source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/@react-native-community/masked-view/android/src/main/AndroidManifest.xml.
> Task :react-native-community_netinfo:processReleaseManifest
package="com.reactnativecommunity.netinfo" found in source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/@react-native-community/netinfo/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.netinfo" from the source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/@react-native-community/netinfo/android/src/main/AndroidManifest.xml.
> Task :react-native-community_masked-view:javaPreCompileRelease
> Task :react-native-community_masked-view:mergeReleaseShaders
> Task :react-native-community_netinfo:generateReleaseRFile
> Task :react-native-community_masked-view:generateReleaseRFile
> Task :react-native-community_masked-view:compileReleaseShaders NO-SOURCE
> Task :expo:preBuild
> Task :expo:preReleaseBuild
> Task :expo:mergeReleaseJniLibFolders
> Task :expo:mergeReleaseNativeLibs
NO-SOURCE
> Task :expo:stripReleaseDebugSymbols
NO-SOURCE
> Task :expo:copyReleaseJniLibsProjectAndLocalJars
> Task :expo:generateReleaseResValues
> Task :expo:extractDeepLinksForAarRelease
> Task :expo-modules-core$android-annotation-processor:processResources
> Task :expo:generateReleaseBuildConfig
> Task :expo:generateReleaseResources
> Task :expo:packageReleaseResources
> Task :expo:parseReleaseLocalResources
> Task :expo:processReleaseManifest
> Task :expo:generateReleaseRFile
> Task :react-native-community_masked-view:extractReleaseAnnotations
> Task :react-native-community_netinfo:extractReleaseAnnotations
> Task :react-native-community_netinfo:javaPreCompileRelease
> Task :expo-constants:createExpoConfig
> Task :expo-constants:preBuild
> Task :expo-constants:preReleaseBuild
> Task :expo-constants:generateReleaseBuildConfig
> Task :expo-modules-core$android-annotation:processResources NO-SOURCE
> Task :expo-constants:generateReleaseResValues
> Task :expo-constants:generateReleaseResources
> Task :expo-constants:packageReleaseResources
> Task :expo-constants:parseReleaseLocalResources
> Task :expo-constants:processReleaseManifest
> Task :expo-constants:generateReleaseRFile
> Task :expo-modules-core:preBuild UP-TO-DATE
> Task :expo-modules-core:preReleaseBuild UP-TO-DATE
> Task :expo-modules-core:generateReleaseBuildConfig
> Task :expo-modules-core:generateReleaseResValues
> Task :expo-modules-core:generateReleaseResources
> Task :expo-modules-core:packageReleaseResources
> Task :expo-modules-core:parseReleaseLocalResources
> Task :expo-modules-core:processReleaseManifest
/home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/AndroidManifest.xml:8:9-11:45 Warning:
	meta-data#com.facebook.soloader.enabled@android:value was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
> Task :expo-modules-core:generateReleaseRFile
> Task :expo-modules-core:javaPreCompileRelease
> Task :expo-constants:javaPreCompileRelease
> Task :expo-file-system:preBuild UP-TO-DATE
> Task :expo-file-system:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:generateReleaseBuildConfig
> Task :expo-file-system:generateReleaseResValues
> Task :expo-file-system:generateReleaseResources
> Task :expo-file-system:packageReleaseResources
> Task :expo-file-system:parseReleaseLocalResources
> Task :expo-file-system:processReleaseManifest
/home/expo/workingdir/build/frontend/node_modules/expo-file-system/android/src/main/AndroidManifest.xml:6:9-8:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
> Task :expo-file-system:generateReleaseRFile
> Task :expo-file-system:javaPreCompileRelease
> Task :expo-font:preBuild UP-TO-DATE
> Task :expo-font:preReleaseBuild UP-TO-DATE
> Task :expo-font:generateReleaseBuildConfig
> Task :expo-font:generateReleaseResValues
> Task :expo-font:generateReleaseResources
> Task :expo-font:packageReleaseResources
> Task :expo-font:parseReleaseLocalResources
> Task :expo-font:processReleaseManifest
> Task :expo-font:generateReleaseRFile
> Task :expo-font:javaPreCompileRelease
> Task :expo-keep-awake:preBuild UP-TO-DATE
> Task :expo-keep-awake:preReleaseBuild UP-TO-DATE
> Task :expo-keep-awake:generateReleaseBuildConfig
> Task :expo-keep-awake:generateReleaseResValues
> Task :expo-keep-awake:generateReleaseResources
> Task :expo-keep-awake:packageReleaseResources
> Task :expo-keep-awake:parseReleaseLocalResources
> Task :expo-keep-awake:processReleaseManifest
> Task :expo-keep-awake:generateReleaseRFile
> Task :expo-keep-awake:javaPreCompileRelease
> Task :expo:javaPreCompileRelease
> Task :expo:mergeReleaseShaders
> Task :expo:compileReleaseShaders NO-SOURCE
> Task :expo:generateReleaseAssets UP-TO-DATE
> Task :expo:packageReleaseAssets
> Task :expo:prepareLintJarForPublish
> Task :expo:prepareReleaseArtProfile
> Task :expo:writeReleaseAarMetadata
> Task :react-native-geolocation-service:preBuild UP-TO-DATE
> Task :react-native-geolocation-service:preReleaseBuild UP-TO-DATE
> Task :react-native-geolocation-service:mergeReleaseJniLibFolders
> Task :react-native-geolocation-service:mergeReleaseNativeLibs NO-SOURCE
> Task :react-native-geolocation-service:stripReleaseDebugSymbols NO-SOURCE
> Task :react-native-geolocation-service:copyReleaseJniLibsProjectAndLocalJars
> Task :react-native-geolocation-service:generateReleaseResValues
> Task :react-native-geolocation-service:extractDeepLinksForAarRelease
> Task :react-native-geolocation-service:generateReleaseBuildConfig
> Task :react-native-geolocation-service:generateReleaseResources
> Task :react-native-geolocation-service:packageReleaseResources
> Task :react-native-geolocation-service:parseReleaseLocalResources
> Task :react-native-geolocation-service:processReleaseManifest
package="com.agontuk.RNFusedLocation" found in source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/react-native-geolocation-service/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.agontuk.RNFusedLocation" from the source AndroidManifest.xml: /home/expo/workingdir/build/frontend/node_modules/react-native-geolocation-service/android/src/main/AndroidManifest.xml.
> Task :react-native-geolocation-service:generateReleaseRFile
> Task :expo-modules-core$android-annotation:compileKotlin
> Task :expo-modules-core$android-annotation:compileJava NO-SOURCE
> Task :expo-modules-core$android-annotation:classes UP-TO-DATE
> Task :expo-modules-core$android-annotation:jar
> Task :expo-modules-core$android-annotation:inspectClassesForKotlinIC
> Task :react-native-geolocation-service:extractReleaseAnnotations
> Task :expo-modules-core$android-annotation-processor:compileKotlin
> Task :expo-modules-core$android-annotation-processor:compileJava NO-SOURCE
> Task :expo-modules-core$android-annotation-processor:classes
> Task :expo-modules-core$android-annotation-processor:jar
> Task :expo-modules-core$android-annotation-processor:inspectClassesForKotlinIC
> Task :react-native-geolocation-service:javaPreCompileRelease
> Task :react-native-community_netinfo:compileReleaseJavaWithJavac
/home/expo/workingdir/build/frontend/node_modules/@react-native-community/netinfo/android/src/main/java/com/reactnativecommunity/netinfo/NetInfoUtils.java:45: error: cannot find symbol
                    receiver, filter, exported ? Context.RECEIVER_EXPORTED : Context.RECEIVER_NOT_EXPORTED);
                                                        ^
  symbol:   variable RECEIVER_EXPORTED
  location: class Context
/home/expo/workingdir/build/frontend/node_modules/@react-native-community/netinfo/android/src/main/java/com/reactnativecommunity/netinfo/NetInfoUtils.java:45: error: cannot find symbol
                    receiver, filter, exported ? Context.RECEIVER_EXPORTED : Context.RECEIVER_NOT_EXPORTED);
                                                                                    ^
  symbol:   variable RECEIVER_NOT_EXPORTED
  location: class Context
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
> Task :react-native-community_netinfo:compileReleaseJavaWithJavac FAILED
> Task :react-native-geolocation-service:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :react-native-community_masked-view:compileReleaseJavaWithJavac
> Task :expo-modules-core:compileReleaseKotlin
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/utilities/EmulatorUtilities.kt:30:13 'SERIAL: String!' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:151:13 Variable 'catalystInstance' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/Promise.kt:72:18 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/Utils.kt:8:3 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/ActivityResultsManager.kt:51:24 Parameter 'activity' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/cdp/CdpNetworkTypes.kt:186:54 Parameter 'request' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/cdp/CdpNetworkTypes.kt:210:54 Parameter 'request' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/cdp/CdpNetworkTypes.kt:230:15 Parameter 'now' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/cdp/CdpNetworkTypes.kt:230:54 Parameter 'request' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/events/KModuleEventEmitterWrapper.kt:90:7 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/jni/JavaScriptObject.kt:90:33 Parameter 'null' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/jni/JavaScriptObject.kt:91:34 Parameter 'null' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/jni/JavaScriptObject.kt:132:5 Parameter 'null' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/sharedobjects/SharedObjectRegistry.kt:54:35 Destructured parameter 'js' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/tracing/ExpoTrace.kt:33:1 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/tracing/ExpoTrace.kt:40:1 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/tracing/ExpoTrace.kt:50:1 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/tracing/ExpoTrace.kt:56:1 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:76:12 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:79:12 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:82:11 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:85:11 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:99:12 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:102:11 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:114:12 Parameter 'type' is never used
w: file:///home/expo/workingdir/build/frontend/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:117:11 Parameter 'type' is never used
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-community_netinfo:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 3m 46s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
102 actionable tasks: 102 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by sugoring** [comment]
expo 로 안드로이드 빌드 후
apk 생성 하였습니다.

각 화면은 작동하는 데, 
서비스키를 활용 하는 부분만 아무런 작동을 하지 않습니다.

------------------------
첫번째, 공공데이터를 활용하는 부분
두번째, react-native-maps를 활용하는 부분
------------------------
서비스키 활용이 문제라고 판단되어 해당 부분을 설명합니다.
첫번째, 공공데이터를 활용하는 부분의 서비스키는 js 파일내에서 활용하고 있습니다.
const serviceKey = 키키키키키
const holidayUrl = `http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getHoliDeInfo?solYear=${year}&solMonth=${month}&ServiceKey=${serviceKey}&_type=json`
두번째, react-native-maps를 활용하는 부분은 app.json에서 활용하고 있습니다.
    "android": {
      "config": {
        "googleMaps": {
          "apiKey": 키키키키키

        }
      },

---------------------------------

권한 설정은 해당과 같이 사용하였습니다.
      "permissions": [
        "INTERNET",
        "ACCESS_NETWORK_STATE",
        "ACCESS_COARSE_LOCATION",
      ],

**Comment by sugoring** [comment]
> expo 로 안드로이드 빌드 후 apk 생성 하였습니다.
> 
> 각 화면은 작동하는 데, 서비스키를 활용 하는 부분만 아무런 작동을 하지 않습니다.
> 
> ## 첫번째, 공공데이터를 활용하는 부분
> 두번째, react-native-maps를 활용하는 부분
> 서비스키 활용이 문제라고 판단되어 해당 부분을 설명합니다. 첫번째, 공공데이터를 활용하는 부분의 서비스키는 js 파일내에서 활용하고 있습니다. const serviceKey = 키키키키키 const holidayUrl = `http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getHoliDeInfo?solYear=${year}&solMonth=${month}&ServiceKey=${serviceKey}&_type=json` 두번째, react-native-maps를 활용하는 부분은 app.json에서 활용하고 있습니다. "android": { "config": { "googleMaps": { "apiKey": 키키키키키
> 
> ```
>     }
>   },
> ```
> 
> 권한 설정은 해당과 같이 사용하였습니다. "permissions": [ "INTERNET", "ACCESS_NETWORK_STATE", "ACCESS_COARSE_LOCATION", ],

안드로이드 빌드 후 네트워크 안되는 에러면,
안드로이드 빌드되면 디폴트로 http 통신을 안하고 https 만 통신할꺼에요

**Comment by sugoring** [comment]
> expo 로 안드로이드 빌드 후 apk 생성 하였습니다.
> 
> 각 화면은 작동하는 데, 서비스키를 활용 하는 부분만 아무런 작동을 하지 않습니다.
> 
> ## 첫번째, 공공데이터를 활용하는 부분
> 두번째, react-native-maps를 활용하는 부분
> 서비스키 활용이 문제라고 판단되어 해당 부분을 설명합니다. 첫번째, 공공데이터를 활용하는 부분의 서비스키는 js 파일내에서 활용하고 있습니다. const serviceKey = 키키키키키 const holidayUrl = `http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getHoliDeInfo?solYear=${year}&solMonth=${month}&ServiceKey=${serviceKey}&_type=json` 두번째, react-native-maps를 활용하는 부분은 app.json에서 활용하고 있습니다. "android": { "config": { "googleMaps": { "apiKey": 키키키키키
> 
> ```
>     }
>   },
> ```
> 
> 권한 설정은 해당과 같이 사용하였습니다. "permissions": [ "INTERNET", "ACCESS_NETWORK_STATE", "ACCESS_COARSE_LOCATION", ],

https://stackoverflow.com/questions/77090627/react-native-expo-android-http-server-network-request-failed

**Comment by sugoring** [comment]
eas build:configure

eas build:configure을 통해서 eas.json파일을 생성해준다.

**Comment by sugoring** [comment]
eas build --platform android --profile semicolons

**Comment by semicolonsknu** [comment]
eas build --platform android --profile semicolons --auto-submit
