### ISSUE TITLE
빌드 시 Google Map이 출력되지 않는 오류

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#48]
> Google API를 사용한 Map 기능이 빌드 후 제대로 출력되지 않는 문제가 발생하고 있습니다.

### TODO 목록
- [x] Google API 키 및 설정 확인
- [x] Map 출력 로직 검토 및 수정
- [x] 수정된 코드 테스트 및 검증

**Comment by sugoring** [comment]
<img width="464" alt="스크린샷 2024-04-23 151921" src="https://github.com/semicolonsknu/knubus/assets/113340465/75d29385-c604-4f07-9bc8-71e7340f3374">
<img width="277" alt="스크린샷 2024-04-23 152038" src="https://github.com/semicolonsknu/knubus/assets/113340465/0cd077ef-e4e5-41aa-8d22-66fe47a94954">
<img width="456" alt="스크린샷 2024-04-23 152345" src="https://github.com/semicolonsknu/knubus/assets/113340465/5071dec3-a97c-4564-8996-c9b49c61fb4b">
<img width="252" alt="스크린샷 2024-04-23 152427" src="https://github.com/semicolonsknu/knubus/assets/113340465/11b40450-1245-4198-b3a8-47cb00430b5d">

**Comment by sugoring** [comment]
https://stackoverflow.com/questions/56635196/how-can-i-store-google-maps-api-keys-not-using-app-json

**Comment by sugoring** [comment]
https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#build-configuration-on-android
