### ISSUE TITLE
날짜 이벤트가 하루씩 밀리는 현상 버그 리포트

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#59]
> 이벤트 날짜가 의도한 날짜보다 하루씩 늦게 표시되는 문제가 발생하고 있습니다.

### TODO 목록
- [x] 날짜 계산 로직 검토 및 수정
- [x] 테스트 케이스 작성 및 실행
- [x] 수정된 코드 배포 및 모니터링

**Comment by sugoring** [comment]
newDate.setDate(newDate.getDate() + 1) 을 사용하여 해결함
