### ISSUE TITLE
모듈화 작업 이슈

### ISSUE THREAD

**Issue by sugoring** [semicolonsknu/knubus#62]
> 현재 모든 기능이 한 파일에 몰려 있어 유지보수와 확장이 어렵습니다. 이를 해결하기 위해 각 기능을 모듈화합니다.

### TODO 목록
- [x] 커스텀 훅 분리: hooks 디렉토리 생성 및 파일 분리
- [x] 유틸리티 함수 모듈화: utils 디렉토리 생성 및 공통 함수 이동
- [x] 스타일 코드 분리: styles 디렉토리 생성 및 스타일 관련 코드 이동
- [x] 화면 컴포넌트 분리: pages 디렉토리 생성 및 각 화면 컴포넌트 파일 분리
- [x] 데이터 관련 코드 분리: data 디렉토리 생성 및 데이터 관련 코드 및 설정 이동
